MarkedList
js-tasks-ru/vue-20211116_aleksey-privalov pull request #4
Opened 2021-11-23 19:26 UTC by Vueger

2021-11-23 19:27 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-11-24 09:42 UTC, ShGKme requested changes
В 01-basics/03-MarkedList требуется подготовить данные в вычисляемом свойстве вместо реализации логики маркировки в коде шаблона.

2021-11-24 09:42 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +          <li v-for="Email in emails" :class="{ marked: filter && Email.toLowerCase().includes(filter.toLowerCase(), pos) }">{{ Email }}</li>
Достаточно сложный код для шаблона. В шаблоне фактически реализована вся логика маркировки email-ов. Это сложно отлаживать, читать, может приводить к проблемам с производительностью. 

Лучше вынести подготовку данных в вычисляемое свойство.

2021-11-24 14:17 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-11-24 14:22 UTC, Vueger commented
Убрал код в метод. Не смог придумать, как в вычисляемое свойство передать параметр (Email из for'а).

2021-11-24 14:22 UTC, closed without merging