MeetupAgenda
js-tasks-ru/vue-20211116_aleksey-privalov pull request #7
Opened 2021-11-30 12:56 UTC by Vueger

2021-11-30 12:57 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-11-30 22:26 UTC, ShGKme requested changes
Директиву `v-show` здесь использовать не корректно...

2021-11-30 22:26 UTC, ShGKme commented on 02-components/03-MeetupCover/MeetupCover.js
> +    }
Вычисляемое свойства - это именно свойства. Для них описывается функция, с помощью которой Vue будет вычислять значение вычисляемого свойства, но оно остаётся свойством. По этой причине вычисляемые свойства принято называть, как свойства, а не как функции (не с глагола, без get).

2021-11-30 22:26 UTC, ShGKme commented on 02-components/05-MeetupAgenda/MeetupAgendaItem.js
>        </div>
Директива `v-show` здесь не подходит. С ней все эти узлы всегда будут выводиться на страницу, даже когда для них нет данных и они не отображаются. Здесь должна использоваться директива `v-if`, с которой ненужные узды не будут рендериться вообще. А `v-show` - для случаев, когда какой-то узел требуется то срывать, то показывать.

2021-12-01 07:33 UTC, Vueger commented on 02-components/03-MeetupCover/MeetupCover.js
> +    }
Хочу спросить, есть ли разница в том, как именовать свойство computed, в кавычках, или без?

2021-12-01 07:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-01 07:47 UTC, ShGKme commented on 02-components/03-MeetupCover/MeetupCover.js
> +    }
Нет. Это не особенность Vue, а имя свойства объекта в JS. Если имя удовлетворяет правилу имён переменной (буквы, цифры (не первая), нижнее подчёркивание), то можно писать без кавычек. А в кавычках можно любую строку.

2021-12-01 07:50 UTC, ShGKme requested changes
Проблема с v-show осталась

2021-12-01 07:50 UTC, ShGKme commented on 02-components/05-MeetupAgenda/MeetupAgendaItem.js
>          </p>
`v-show` остался. И лучше проверять тип по непосредственно типу - `agendaItem.type === 'talk'`

2021-12-01 07:58 UTC, Vueger commented
> Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

Система тестирования и MeetupView тоже проверяет? Я эту задачу только скачал, ещё не приступал к решению. Сдаю только MeetupCover и MeetupAgenda.

2021-12-01 08:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-01 08:01 UTC, Vueger commented on 02-components/05-MeetupAgenda/MeetupAgendaItem.js
>          </p>
Почему Вы всегда три "равно" пишете? Я, когда на JS раньше программировал, всегда два "равно" писал, только в НЕКОТОРЫХ случаях три (когда это необходимо было). Сейчас правила поменялись? :)

2021-12-01 16:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-01 17:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-01 17:09 UTC, Vueger commented
Странно, что тест не проходит. Локально все тесты проходят ОК.

2021-12-01 17:13 UTC, ShGKme commented on 02-components/05-MeetupAgenda/MeetupAgendaItem.js
>          </p>
Всегда использовать строгое сравнение вместо нестрого - один из самых часто используемых правил, которое обычно включают в линтерах.

В нестрогом `==` очень не очевидно, как именно сработает сравнение, больной набор правил: https://dorey.github.io/JavaScript-Equality-Table/

2021-12-01 17:14 UTC, ShGKme commented
> > Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).
> 
> Система тестирования и MeetupView тоже проверяет? Я эту задачу только скачал, ещё не приступал к решению. Сдаю только MeetupCover и MeetupAgenda.

Система запускает все тесты репозитория. Если задача есть в ветке, которая вливается, её тесты будут запущены.

2021-12-01 17:16 UTC, ShGKme commented on 02-components/06-MeetupView/MeetupView.js
> +import MeetupInfo from './MeetupInfo.js';
Вы импортируете эти модули в решении, но не закоммитили их, они отсутствуют в репозитории. По этой причине тесты не проходят на GitHub, но проходят локально - файлы в репозитории и локальные разные.

2021-12-02 05:39 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-12-02 13:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-12-02 21:21 UTC, ShGKme approved these changes
Все задачи приняты 🎉

2021-12-02 21:21 UTC, ShGKme commented on 02-components/07-PageMeetup/PageMeetup.js
> +	},
Обычно не комментирую форматирование, но здесь что-то куда-то сильно уехало :)

2021-12-02 21:22 UTC, merged

2021-12-03 08:46 UTC, Vueger commented on 02-components/07-PageMeetup/PageMeetup.js
> +	},
А у меня всё красиво в редакторе, Visual Studio Code который. :)
В Notepad++, да, видна проблема...
![image](https://user-images.githubusercontent.com/94059865/144572560-0f758208-e38f-43d8-9d1b-872769a2343b.png)
![image](https://user-images.githubusercontent.com/94059865/144572751-c25a3144-40e2-40cf-946b-ceff3145e81b.png)

2021-12-03 08:48 UTC, Vueger commented on 02-components/07-PageMeetup/PageMeetup.js
> +	},
Вообще, я не люблю символ Tab использовать. Он везде по своему себя ведёт. Обычно стараюсь пробелами отступы делать. Как правило, 2 пробела = 1 отступ.

2021-12-03 16:12 UTC, ShGKme commented on 02-components/07-PageMeetup/PageMeetup.js
> +	},
Обычно редакторы настраиваются так, чтобы автоматически при нажатии на кнопку Tab вставлять именно пробелы.

Также эту замену делают линтеры/форматеры, например, prettier. В Visual Studio Code можно подключать плагин для автоматического применения при сохранении.

Добавлю, что рекомендую использовать VS Code вместо Notepad++. Последний сильно уступает в возможностях современным редакторам. Если хочется чего-то лёгкого, можно также посмотреть на Sublime Text, но он условно платный и расширения ставить по-сложнее, возможностей меньше...